modLoader="javafml"
loaderVersion="[33,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/WoolButtons/blob/1.16/LICENSE"

[[mods]]
	modId="sbmwoolbuttons"
	version="v1.1"
	displayName="Wool Buttons"
	description='''Adds buttons made of wool.'''
	issueTrackerURL="https://github.com/bl4ckscor3/WoolButtons/issues"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wool-buttons"
	authors="bl4ckscor3, DarkGuardsman"

[[dependencies.sbmwoolbuttons]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmwoolbuttons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"