modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory

[[mods]] #mandatory
	modId="sbmwoolbuttons" #mandatory
	version="0.0.1" #mandatory
	displayName="[SBM] Wool Buttons" #mandatory
	description='''Adds buttons made of wool.''' #mandatory
	issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-WoolButtons/issues"
	displayURL="http://minecraft.curseforge.com/projects/sbm-wool-buttons"
	authors="bl4ckscor3"

[[dependencies.sbmwoolbuttons]]
    modId="forge"
    mandatory=true
    versionRange="[25.0.168,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmwoolbuttons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"